from __future__ import annotations

import hashlib
import json
import logging
import re
from collections import OrderedDict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup
from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
from playwright.sync_api import sync_playwright

from scraper.models import ReportRecord

logger = logging.getLogger(__name__)

BASE_URL = (
    "https://www.leaguesecretary.com/"
    "bowling-centers/west-seattle-bowl/"
    "bowling-leagues/rainbowlers-league-c21/"
    "dashboard/122895"
)

ALLOWED_HOST = "www.leaguesecretary.com"
LEAGUE_ID = "122895"

REPORT_PATH_MARKERS = (
    "/league/standings/",
    "/league/recaps/",
    "/league/results/",
    "/league/schedule/",
    "/league/statistics/",
    "/league/stats/",
    "/bowler/history/",
    "/team/history/",
)

REPORT_KEYWORDS = (
    "standings",
    "recap",
    "stats",
    "statistics",
    "results",
    "schedule",
    "performance",
    "bowler",
    "team",
    "history",
    "average",
)

SEASON_PATTERNS = (
    re.compile(r"\b20[2-9]\d\b", re.IGNORECASE),
    re.compile(r"(?:Fall|Winter|Spring|Summer)\s+20[2-9]\d", re.IGNORECASE),
)

WEEK_PATTERNS = (
    re.compile(r"\bweek\s*#?\d+\b", re.IGNORECASE),
    re.compile(r"\b(?:round|match|game)\s*#?\d+\b", re.IGNORECASE),
)


class LeagueSecretaryScraper:
    """Discover and save public League Secretary HTML reports."""

    def __init__(
        self,
        output_dir: Path | str = "data",
        dashboard_url: str = BASE_URL,
        user_agent: str = "WSBtool/RainbowlersLeagueScraper/1.0",
    ) -> None:
        self.output_dir = Path(output_dir)
        self.raw_dir = self.output_dir / "raw"
        self.index_path = self.output_dir / "index.json"
        self.dashboard_url = dashboard_url
        self.user_agent = user_agent

        self.session = requests.Session()
        self.session.headers.update(
            {
                "User-Agent": user_agent,
                "Accept": (
                    "text/html,application/xhtml+xml,"
                    "application/xml;q=0.9,*/*;q=0.8"
                ),
                "Accept-Language": "en-US,en;q=0.9",
            }
        )

    def run(self, backfill: bool = False) -> dict[str, Any]:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.raw_dir.mkdir(parents=True, exist_ok=True)

        state = self._load_index()
        result: dict[str, Any] = {
            "fetched": 0,
            "skipped": 0,
            "errors": [],
            "discovered": 0,
            "records": 0,
        }

        try:
            dashboard_html = self._fetch_text(self.dashboard_url)
            self._save_text_file(
                self.raw_dir / "dashboard.html",
                dashboard_html,
            )

            logger.info(
                "Fetched dashboard: url=%s html_bytes=%d",
                self.dashboard_url,
                len(dashboard_html.encode("utf-8")),
            )

            reports = self.discover_reports(
                dashboard_html,
                self.dashboard_url,
            )

            logger.info(
                "Discovered %d links on dashboard",
                len(reports),
            )

            # Inspect report-family pages. The bowler history family is
            # included because its individual links may be generated by JS.
            family_reports = [
                report
                for report in reports
                if self._is_report_family(report.url)
            ]

            for family_report in family_reports:
                try:
                    family_html = self._fetch_family_html(
                        family_report.url
                    )

                    family_links = self.discover_reports(
                        family_html,
                        family_report.url,
                    )

                    reports.extend(family_links)

                    logger.info(
                        "Discovered %d links from %s",
                        len(family_links),
                        family_report.url,
                    )

                except Exception as exc:
                    self._add_error(
                        result,
                        family_report.url,
                        exc,
                    )
                    logger.warning(
                        "Could not inspect report family %s: %s",
                        family_report.url,
                        exc,
                    )

            reports = self._deduplicate_reports(reports)
            result["discovered"] = len(reports)

            # Do not publish family pages as final reports. They are only
            # navigation pages used to discover detailed report URLs.
            detail_reports = [
                report
                for report in reports
                if not self._is_report_family(report.url)
            ]

            detail_reports = [
                report
                for report in detail_reports
                if (
                    report.season == "Unknown season"
                    or self._is_supported_season(
                        report.season,
                        report.url,
                    )
                )
            ]

            if backfill:
                selected_reports = detail_reports
            else:
                selected_reports = self._select_latest_reports(
                    detail_reports
                )

            logger.info(
                "Selected %d reports from %d filtered reports",
                len(selected_reports),
                len(detail_reports),
            )

            for report in selected_reports:
                logger.info(
                    "Selected report: kind=%s season=%s week=%s url=%s",
                    report.kind,
                    report.season,
                    report.week,
                    report.url,
                )

                try:
                    self._fetch_and_store_report(
                        report,
                        state,
                        result,
                    )
                except Exception as exc:
                    self._add_error(
                        result,
                        report.url,
                        exc,
                    )
                    logger.warning(
                        "Failed to fetch report %s: %s",
                        report.url,
                        exc,
                    )

            self._save_index(state)
            result["records"] = len(state)
            return result

        except Exception as exc:
            self._add_error(
                result,
                self.dashboard_url,
                exc,
            )
            logger.exception("Dashboard fetch failed")
            self._save_index(state)
            return result

    def discover_reports(
        self,
        html: str,
        base_url: str,
    ) -> list[ReportRecord]:
        """Discover report links from HTML, including iframe HTML."""

        soup = BeautifulSoup(html, "html.parser")
        seen: dict[str, ReportRecord] = OrderedDict()

        for tag in soup.select("a[href]"):
            href = tag.get("href", "").strip()

            if not href:
                continue

            if href.startswith(
                (
                    "javascript:",
                    "mailto:",
                    "tel:",
                )
            ):
                continue

            target = urljoin(
                base_url,
                href,
            ).split("#", 1)[0]

            parsed = urlparse(target)
            path = parsed.path.lower()

            if (
                parsed.netloc
                and parsed.netloc.lower() != ALLOWED_HOST
            ):
                continue

            if self._is_subscription_pdf(target):
                continue

            if LEAGUE_ID not in parsed.path:
                continue

            text = " ".join(
                tag.get_text(
                    " ",
                    strip=True,
                ).split()
            )

            combined = f"{text} {target}".lower()

            is_report_path = any(
                marker in path
                for marker in REPORT_PATH_MARKERS
            )

            has_report_keyword = any(
                keyword in combined
                for keyword in REPORT_KEYWORDS
            )

            if not is_report_path and not has_report_keyword:
                continue

            report = ReportRecord(
                url=target,
                title=(
                    text or self._title_from_path(path)
                )[:200],
                season=self._extract_season(
                    text,
                    target,
                ),
                week=self._extract_week(
                    text,
                    target,
                ),
                kind=self._infer_kind(
                    text,
                    target,
                ),
            )

            seen[target.lower()] = report

        return list(seen.values())

    def _fetch_family_html(self, url: str) -> str:
        """Fetch a family page and include rendered iframe content."""

        # First try the ordinary response. This is enough when the family
        # page contains normal anchor tags.
        raw_html = self._fetch_text(url)

        if self._contains_detailed_report_link(raw_html):
            return raw_html

        # Some family pages construct their links with JavaScript.
        return self._fetch_rendered_html(
            url,
            save_diagnostics=True,
        )

    def _fetch_and_store_report(
        self,
        report: ReportRecord,
        state: dict[str, dict[str, Any]],
        result: dict[str, Any],
    ) -> None:
        if self._is_subscription_pdf(report.url):
            logger.info(
                "Skipping subscription-protected PDF: %s",
                report.url,
            )
            return

        logger.info(
            "Loading JavaScript-rendered report: %s",
            report.url,
        )

        report_html = self._fetch_rendered_html(
            report.url,
            save_diagnostics=True,
        )

        content_hash = hashlib.sha256(
            report_html.encode(
                "utf-8",
                errors="replace",
            )
        ).hexdigest()

        key = self._record_key(report)

        if (
            key in state
            and state[key].get("sha256") == content_hash
        ):
            result["skipped"] += 1
            return

        url_hash = hashlib.sha256(
            report.url.encode("utf-8")
        ).hexdigest()[:20]

        destination = self.raw_dir / f"{url_hash}.html"
        self._save_text_file(destination, report_html)

        saved = ReportRecord(
            url=report.url,
            title=report.title,
            season=report.season,
            week=report.week,
            kind=report.kind,
            sha256=content_hash,
            raw_file=str(
                destination.relative_to(self.output_dir)
            ),
            fetched_at=datetime.now(
                timezone.utc
            ).isoformat(),
            source="League Secretary",
        )

        state[key] = saved.to_dict()
        result["fetched"] += 1

        logger.info(
            "Saved report: %s",
            destination,
        )

    def _fetch_text(self, url: str) -> str:
        response = self.session.get(
            url,
            timeout=45,
        )
        response.raise_for_status()

        content_type = response.headers.get(
            "content-type",
            "",
        ).lower()

        path = urlparse(url).path.lower()

        if (
            "html" not in content_type
            and not path.endswith(
                (
                    "/",
                    ".html",
                )
            )
        ):
            raise ValueError(
                "Expected HTML but received "
                f"{content_type or 'unknown content type'}"
            )

        return response.text

    def _fetch_rendered_html(
        self,
        url: str,
        save_diagnostics: bool = False,
    ) -> str:
        """Render a page and return the document containing report data."""

        url_hash = hashlib.sha256(
            url.encode("utf-8")
        ).hexdigest()[:20]

        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(
                headless=True,
            )

            try:
                page = browser.new_page(
                    user_agent=self.user_agent,
                    viewport={
                        "width": 1440,
                        "height": 1200,
                    },
                )

                page.on(
                    "console",
                    lambda message: logger.info(
                        "BROWSER CONSOLE [%s]: %s",
                        message.type,
                        message.text,
                    ),
                )

                page.on(
                    "pageerror",
                    lambda error: logger.error(
                        "BROWSER PAGE ERROR: %s",
                        error,
                    ),
                )

                page.on(
                    "requestfailed",
                    lambda request: logger.error(
                        "REQUEST FAILED: %s %s",
                        request.url,
                        request.failure,
                    ),
                )

                page.goto(
                    url,
                    wait_until="domcontentloaded",
                    timeout=60_000,
                )

                try:
                    page.wait_for_load_state(
                        "networkidle",
                        timeout=30_000,
                    )
                except PlaywrightTimeoutError:
                    logger.warning(
                        "Network did not become idle for %s",
                        url,
                    )

                # Wait for either a table or a visible report container.
                try:
                    page.wait_for_selector(
                        "table",
                        timeout=30_000,
                    )
                except PlaywrightTimeoutError:
                    logger.warning(
                        "No table found on %s; waiting before capture",
                        url,
                    )
                    page.wait_for_timeout(5_000)

                if save_diagnostics:
                    page.screenshot(
                        path=str(
                            self.raw_dir
                            / f"{url_hash}-browser.png"
                        ),
                        full_page=True,
                    )

                logger.info(
                    "Page frame count: %d",
                    len(page.frames),
                )

                candidates: list[tuple[int, str, str]] = []

                for index, frame in enumerate(page.frames):
                    try:
                        frame_html = frame.content()
                        frame_text = frame.locator(
                            "body"
                        ).inner_text(
                            timeout=5_000
                        )

                        logger.info(
                            "Frame %d: url=%s html_bytes=%d "
                            "text_chars=%d tables=%d",
                            index,
                            frame.url,
                            len(frame_html.encode("utf-8")),
                            len(frame_text),
                            frame.locator("table").count(),
                        )

                        if save_diagnostics:
                            self._save_text_file(
                                self.raw_dir
                                / f"{url_hash}-frame-{index}.html",
                                frame_html,
                            )

                        # Prefer frames with tables and substantial text.
                        score = (
                            frame.locator("table").count() * 1_000_000
                            + len(frame_text)
                        )

                        candidates.append(
                            (
                                score,
                                frame.url,
                                frame_html,
                            )
                        )

                    except Exception as exc:
                        logger.warning(
                            "Could not capture frame %d at %s: %s",
                            index,
                            frame.url,
                            exc,
                        )

                outer_html = page.content()

                if save_diagnostics:
                    self._save_text_file(
                        self.raw_dir
                        / f"{url_hash}-rendered.html",
                        outer_html,
                    )

                logger.info(
                    "Rendered report: url=%s html_bytes=%d",
                    url,
                    len(outer_html.encode("utf-8")),
                )

                if candidates:
                    best_score, best_url, best_html = max(
                        candidates,
                        key=lambda item: item[0],
                    )

                    logger.info(
                        "Selected rendered frame: url=%s score=%d "
                        "html_bytes=%d",
                        best_url,
                        best_score,
                        len(best_html.encode("utf-8")),
                    )

                    return best_html

                return outer_html

            finally:
                browser.close()

    def _contains_detailed_report_link(self, html: str) -> bool:
        soup = BeautifulSoup(html, "html.parser")

        for tag in soup.select("a[href]"):
            href = tag.get("href", "")
            path = urlparse(href).path.lower()

            if re.search(
                r"/(?:202[6-9]|20[3-9]\d)/",
                path,
            ):
                return True

        return False

    def _is_report_family(self, url: str) -> bool:
        path = urlparse(url).path.rstrip("/").lower()

        family_paths = (
            f"/league/standings/{LEAGUE_ID}",
            f"/league/recaps/{LEAGUE_ID}",
            f"/league/results/{LEAGUE_ID}",
            f"/league/schedule/{LEAGUE_ID}",
            f"/league/statistics/{LEAGUE_ID}",
            f"/league/stats/{LEAGUE_ID}",
            f"/bowler/history/{LEAGUE_ID}",
        )

        return path in family_paths

    def _is_subscription_pdf(self, url: str) -> bool:
        lower_url = url.lower()

        return (
            lower_url.endswith(".pdf")
            or "/reports/shared" in lower_url
        )

    def _is_supported_season(
        self,
        season: str,
        url: str,
    ) -> bool:
        text = f"{season} {url}"
        years = re.findall(
            r"20([2-9]\d)",
            text,
        )

        return any(
            int(year) >= 26
            for year in years
        )

    def _extract_season(
        self,
        title: str,
        url: str,
    ) -> str:
        text = f"{title} {url}"

        for pattern in SEASON_PATTERNS:
            match = pattern.search(text)

            if match:
                return match.group(0)

        for part in urlparse(url).path.split("/"):
            if re.fullmatch(
                r"20[2-9]\d",
                part,
            ):
                return part

        return "Unknown season"

    def _extract_week(
        self,
        title: str,
        url: str,
    ) -> str:
        text = f"{title} {url}"

        for pattern in WEEK_PATTERNS:
            match = pattern.search(text)

            if match:
                return match.group(0)

        path_parts = [
            part
            for part in urlparse(url).path.split("/")
            if part
        ]

        for index, part in enumerate(path_parts):
            if re.fullmatch(
                r"20[2-9]\d",
                part,
            ):
                remaining = path_parts[index + 1 :]

                if (
                    len(remaining) >= 2
                    and remaining[1].isdigit()
                ):
                    return f"Week {remaining[1]}"

                break

        if (
            "bowler" not in url.lower()
            and path_parts
            and path_parts[-1].isdigit()
        ):
            return f"Report {path_parts[-1]}"

        return "Unknown week"

    def _infer_kind(
        self,
        title: str,
        url: str,
    ) -> str:
        text = f"{title} {url}".lower()

        if "/league/standings/" in text:
            return "standings"

        if "/league/recaps/" in text:
            return "recap"

        if "/bowler/history/" in text:
            return "bowler history"

        if "/team/history/" in text:
            return "team history"

        for keyword in (
            "statistics",
            "stats",
            "results",
            "schedule",
            "performance",
            "history",
        ):
            if keyword in text:
                return keyword

        return "report"

    def _select_latest_reports(
        self,
        reports: list[ReportRecord],
    ) -> list[ReportRecord]:
        return sorted(
            reports,
            key=lambda report: (
                self._season_sort_key(report.season),
                self._week_sort_key(report.week),
                report.url,
            ),
            reverse=True,
        )[:20]

    def _season_sort_key(
        self,
        season: str,
    ) -> tuple[int, str]:
        match = re.search(
            r"20([2-9]\d)",
            season,
        )

        return (
            int(match.group(1))
            if match
            else 0,
            season,
        )

    def _week_sort_key(self, week: str) -> int:
        match = re.search(
            r"(?:week|report)\s*(\d+)",
            week,
            re.IGNORECASE,
        )

        return int(match.group(1)) if match else 0

    def _deduplicate_reports(
        self,
        reports: list[ReportRecord],
    ) -> list[ReportRecord]:
        unique: dict[str, ReportRecord] = OrderedDict()

        for report in reports:
            unique[report.url.lower()] = report

        return list(unique.values())

    def _record_key(
        self,
        report: ReportRecord,
    ) -> str:
        return (
            f"{report.season}|"
            f"{report.week}|"
            f"{report.url}"
        ).lower()

    def _load_index(self) -> dict[str, dict[str, Any]]:
        if not self.index_path.exists():
            return {}

        try:
            payload = json.loads(
                self.index_path.read_text(
                    encoding="utf-8",
                )
            )

            records = payload.get(
                "records",
                {},
            )

            return records if isinstance(
                records,
                dict,
            ) else {}

        except (
            json.JSONDecodeError,
            OSError,
        ):
            logger.warning(
                "Could not read %s; starting with empty index",
                self.index_path,
            )
            return {}

    def _save_index(
        self,
        state: dict[str, dict[str, Any]],
    ) -> None:
        payload = {
            "league": "Rainbowlers League",
            "records": state,
            "updated_at": datetime.now(
                timezone.utc
            ).isoformat(),
        }

        self.index_path.write_text(
            json.dumps(
                payload,
                indent=2,
                sort_keys=True,
            ),
            encoding="utf-8",
        )

    def _save_text_file(
        self,
        path: Path,
        content: str,
    ) -> None:
        path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        path.write_text(
            content,
            encoding="utf-8",
        )

    def _title_from_path(self, path: str) -> str:
        value = (
            path.rstrip("/")
            .split("/")[-1]
            .replace("-", " ")
        )

        return value.title() or "League Secretary report"

    def _add_error(
        self,
        result: dict[str, Any],
        url: str,
        exc: Exception,
    ) -> None:
        result["errors"].append(
            {
                "url": url,
                "error": str(exc),
            }
        )


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s:%(message)s",
    )

    scraper = LeagueSecretaryScraper(
        output_dir="data",
    )

    print(
        json.dumps(
            scraper.run(
                backfill=False,
            ),
            indent=2,
            sort_keys=True,
        )
    )
